export default function Head() {
    return (
      <>

        {/* <title>NextJs 13 Data Fetching tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <title>Nexus proxy service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="google-site-verification" content="42ux6T3xJnhWsNxQAtJfULFLO_HJCz88PKqhYbUjvp0" />
        <link rel="icon" href="/next.svg" />
    
      </>
    )
  }