import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { getTodos } from "@/lib/connect";

const inter = Inter({ subsets: ["latin"] });
// export async function getServerSideProps() {
//  // gets the todo from our backend
//   const data = await getTodos();
// // converts the array to json

//   return {
//     props: {
//       data: JSON.parse(JSON.stringify(data)),
//     },
//   };
// }
export default function Home() {
// using the json as prop in our functional component
const xyxData=[
  {
      "collectionId": "vqfexf5ju8w3weq",
      "collectionName": "todos",
      "created": "2023-01-23 03:42:34.035Z",
      "id": "72a45ai2y63y01n",
      "text": "working on new project",
      "updated": "2023-01-23 03:42:34.035Z",
      "expand": {}
  },
  {
      "collectionId": "vqfexf5ju8w3weq",
      "collectionName": "todos",
      "created": "2023-01-23 03:04:31.097Z",
      "id": "7y5y6euw8hy6q01",
      "text": "write some more code",
      "updated": "2023-01-23 03:04:31.097Z",
      "expand": {}
  },
  {
      "collectionId": "vqfexf5ju8w3weq",
      "collectionName": "todos",
      "created": "2023-01-23 03:04:12.808Z",
      "id": "wpy1npqkbbfau5y",
      "text": "write some code",
      "updated": "2023-01-23 03:04:12.808Z",
      "expand": {}
  },
  {
      "collectionId": "vqfexf5ju8w3weq",
      "collectionName": "todos",
      "created": "2023-01-23 03:04:03.340Z",
      "id": "llup3btg61qn00k",
      "text": "make video",
      "updated": "2023-01-23 03:04:03.340Z",
      "expand": {}
  }
]



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          {/*map through the array and displays the todo text*/}
          {xyxData.map((record: any) => (
            <div key={record.id} className={styles.card}>
              <p className={inter.className}>{record.text}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
